deploy:
  provider: gae
  keyfile: client-secret.json
  project: devops2-test
language: php
php:
- '5.5'
- '5.6'
notifications:
  slack:
    secure: KFE45tJ+T8+swKZOpvnh1GlGCqkimQ0b7guFtMOsWsx4HZxvGw6i3p1FB5CSaYKOSKfqZfy6bIcMNDQUr0huHnjK9CWn0a/59uycC6Dm7Zwx8GHVyiHlSeyEDLXJoD2z1hMdR17ZjB6OhX/4/Tatt2NX/TmeoNtdh6NTsSRvgJCL0LC8MMAyk2PxDlq6IpBmRFBoDIKHnNcAprEjl1THl2RytgARhBbpUgGDvwzkLodUZUcMQJoF4zMVpdxCpl0er61sgBzeI1rFBCwTavSdHDV577XEDrbX0I971CgX8HFlxf97QFzyS/IliBDEisEeGUp1taRoYFdwPZcV8EVW0BDCnn7QrUTAAyqh7lSxD6m+sRQ9mwlTN+bpYRQG52juz8y2R4Ok4PwDxzTfi8cJHDbNNlJUHpSWlRYvxX34HWrRRHv/cOYI5xbLRKeXrXN8XChvedor6/ni6yLn2o5V3EqM1t9hCNfi5RU8yjhLbsVcnHP4GBLM7l43diASuLILjWkT3rk8RXDF9G+ZlC/NRA9CDYtKyY8lPJkPY6dVLGkGa1KIQV0Ej49THHsJy3TlCvL348tk9vYNLLbRWRQKF8a0x1Kzp7xaS2xsdgWzwlOE6QaIcAZU4mZdU9M+30G6155AjTFd+gg6/mpRcUw50VKb2qkWXiyh7F7aIHtb9tA=
before_install:
- openssl aes-256-cbc -K $encrypted_fd90c7745918_key -iv $encrypted_fd90c7745918_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
install: composer install
